# action.yml
# az keyvault secret show --name "special-secret" --vault-name "secret-stuff" --query "value"
name: 'Hello World'
description: 'Greet someone and record the time'
branding:
  icon: lock
  color: yellow

inputs:
  vaultName:  # id of input
    description: 'The vault to read from'
    required: true
  objectType:
    description: 'The type of resource to get (secret, key, certificate)'
    default: 'secret'
    required: true
  objectKeys:
    description: 'The keys of the resource to get (comma-seperated)'
    required: true
  outputEnvs:
    description: 'Create environment variables from the keys? (true/false)'
    required: false
    default: 'true'
  outputOutputs:
    description: 'Create outputs variables from the keys? (true/false)'
    required: false
    default: 'false'
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'