# action.yml
# az keyvault secret show --name "special-secret" --vault-name "secret-stuff" --query "value"
name: 'Hello World'
description: 'Greet someone and record the time'
branding:
  icon: lock
  color: yellow

inputs:
  vault-name:  # id of input
    description: 'The vault to read from'
    required: true
  type:
    description: 'The type of resource to get (secret, key, certificate)'
    default: 'secret'
    required: true
  keys:
    description: 'The keys of the resource to get (comma-seperated)'
    required: true
  output-env:
    description: 'Create environment variables from the keys?'
    required: true
    default: 'true'
  output-outputs:
    description: 'Create outputs variables from the keys?'
    required: true
    default: 'false'
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.vault-name }}
    - ${{ inputs.type }}
    - ${{ inputs.keys }}
    - ${{ inputs.output-env }}
    - ${{ inputs.output-outputs }}